table products_dataset
	lineageTag: f1fed00f-4978-4f51-a4f4-bced5f56b76c

	column product_id
		dataType: string
		lineageTag: 61569281-aa04-437b-b6da-a84da25241bb
		summarizeBy: none
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column product_name
		dataType: string
		lineageTag: 4252c550-6f69-4810-be22-34bdafeb55ab
		summarizeBy: none
		sourceColumn: product_name

		annotation SummarizationSetBy = Automatic

	column category
		dataType: string
		lineageTag: 17b73c48-ae90-41da-9335-26f4b81041cb
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	column price_per_unit
		dataType: double
		lineageTag: 2ff2d852-5ab5-4512-9030-18cdc7af1cc3
		summarizeBy: none
		sourceColumn: price_per_unit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column brand
		dataType: string
		lineageTag: 1e55a7c4-ec85-4d51-95e9-ea016243963a
		summarizeBy: none
		sourceColumn: brand

		annotation SummarizationSetBy = Automatic

	column product_description
		dataType: string
		lineageTag: 178f1cd9-42a7-4c5a-bae5-08456c7f21e1
		summarizeBy: none
		sourceColumn: product_description

		annotation SummarizationSetBy = Automatic

	partition products_dataset = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("D:\Workspace\Dashboard\dashboard\dados\products_dataset.csv"),[Delimiter=",", Columns=6, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado com Localidade" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos", {{"price_per_unit", type number}}, "en-US")
				in
				    #"Tipo Alterado com Localidade"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

